### ISSUE TITLE
Generate a map using SLAM

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/SLAM#20]
**Description:**
- Generate a map using SLAM and save it

**Goals:**
- [x] Decide on SLAM library
- [x] Interface SLAM with Nav Stack
- [x] Generate a map using SLAM & save it

**Acceptance Criteria:**
- [x] Map can be generated for any world and saved

**Notes:**
- Assume the robot being used is in simulation, but keep track of any changes to the code base required for deploying on any robot (be it physical or other simulation)
- Some SLAM libraries: [gmapping](http://wiki.ros.org/gmapping) and [rtab map](http://wiki.ros.org/rtabmap)
- Don’t just randomly choose the SLAM library, a reason is needed to validate your decision
- Generated maps should be loadable by #19 
- Generate maps into a folder and keep it clean (name the saved maps appropriately)
- ~~Generating the map also includes figuring out how to move the robot within the world in order to generate the map (teleoperation)~~
  - ~~It would be cool if the robot can generate autonomously by only specifying key nav goals to navigate to!~~
- See Chp 9 of Programming Robots with ROS as reference

**Comment by Abijay1998** [comment]
Some research papers/starting points 

SLAM packages comparison - [SPR13-SSRR13.pdf](https://github.com/UTRA-ART/SLAM/files/3834199/SPR13-SSRR13.pdf)

how to benchmark b/w slam packages -
https://answers.ros.org/question/318916/benchmarking-between-slam-alghoritms/

Slam comparison -
https://ieeexplore.ieee.org/document/8327175
