### ISSUE TITLE
Ensure Caffeine + Husky works with all our Packages

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/SLAM#65]
**Description**:
- Now that Navigation with LIDAR is coming to a close, we need to ensure all our packages are structured correctly and work both with Husky and Caffeine (in simulation and reality)
- **NOTE:** Given the open ended-ness of this task, add new Goals (issues to solve) below as they appear

**Goals**: (add as more issues come to light)
- [x] Correct map update rate (observed in Real run)
- [x] Create correct transform tree with all our sensors connected
- [x] Add necessary package dependencies in `package.xml`

**Acceptance Criteria**:
- [x] Husky simulation runs Gmapping, Nav Stack, and `robot_localization` correctly with no outstanding errors/warnings
- [x] Caffeine simulation runs Gmapping, Nav Stack, and `robot_localization` correctly with no outstanding errors/warnings
- [x] ~~Caffeine physical robot runs Gmapping, Nav Stack, and `robot_localization` correctly with no outstanding errors/warnings~~ will be verified by issue #43 
- [x] Packages are structured in a consistent fashion with a clear modular design

**Notes**:
- This issue is open ended as to what changes need to be made but should account for enabling packages to be swapped with little has and be easy to maintain
- Modular design ensures that adding a new "parameter" minimizes the number of files to be changed

**Comment by AbiJaya1998** [comment]
Useful links - 

- https://answers.ros.org/question/232794/can-i-use-robot_localization-package-with-only-imu-data-if-i-couldhow-to-config-the-package/?fbclid=IwAR3GRRWsmc-XAUDfkJ0w4BpsmkeCT-1Bxf1fqcW0JxHACSsbonIBxIIhd60

- https://answers.ros.org/question/216856/robot_localization-drift/?fbclid=IwAR0sIqdQzK2exF4PeOfoiylLa_oQepx7UG4_yfxc0tx-EQ10aZjnwQZoHZk

**Comment by AbiJaya1998** [comment]
Imp observations 
- Use both odom and IMU firstly 

![image](https://user-images.githubusercontent.com/43094233/73223086-e71f9b80-4132-11ea-8713-b1bf61d356df.png)

**Comment by AbiJaya1998** [comment]
More Useful links -
https://answers.ros.org/question/229722/how-to-stop-gazebo-publishing-tf/
