### ISSUE TITLE
Create Custom RViz Configuration for Caffeine

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/SLAM#76]
**Description:**
- Create a custom rviz configuration that displays relevant information produced by Caffeine sensors

**Goals:**
- [x] Save an Rviz configuration
- [x] Load an Rviz configuration
- [x] Display filtered Odometry from /odom, /odometry/filtered, /stereo_odometer/odometry 
- [x] Display filtered LIDAR scan from /scan, /scan_filtered
- [x] Display using Odom fixed frame
- [x] Display Point Clouds from /scan_map
- [x] Display Camera stream from ../right/image_rect and ../left/image_rect
- [x] Display Navigation info (/map, /odom, /base-link frames)
- [x] Use Top down Ortho View by default
- [x] Display TF with axes (not with names; use TF) 
- [x] Display depth images in RViz 

**Acceptance Criteria:**
- [x] `roslaunch caffeine caffeine_rviz` displays all relevant topics without need to manually add topics
- [x] Documentation explaining how to modify the rviz configuration (be it through code or using the GUI)

**Notes:**
- If you can save an rviz configurations from the rviz GUI, then it may be easier to make them by hand instead of learning the rviz configuration structure

**Comment by tcheung99** [comment]
Enabled all TF Frames
