### ISSUE TITLE
Retrieving Way-points during IGVC

### ISSUE THREAD

**Issue by erickmu1** [UTRA-ART/SLAM#90]
**Description:**
- Need to know how we will get navigation waypoints during IGVC competition and save them for our use in navigation

**Goals:**
- [x] Read the IGVC rules (Auto-Nav challenge) in more details to learn how we get the waypoints
  - [x] Implement code to receive waypoints if needed

**Acceptance Criteria:**
- [x] We know how we will retrieve competition waypoints and necessary code exists to get them

**Notes:**
- I believe they will tell us the waypoints (as GPS coordinates) beforehand, so we should be able to store them in a static file. But this needs to be double checked!

**Comment by chandra-gummaluru** [comment]
From the [IGVC 2020 rules](http://www.igvc.org/2020rules.pdf):
>  One waypoint pair will be the entrance and exit of the
course in No Man’s Land. There will be two additional waypoints in No-Man’s Land. 

There is no other information about way-points, and so we assume we will need to manually enter them into our system.

We'll assume we can store the waypoints in a text-file, and write a service node that reads from this text-file (see #93).
